/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AboutSetting: typeof import('./../components/settings_view/AboutSetting.vue')['default']
    AButton: typeof import('ant-design-vue/es')['Button']
    ACheckboxGroup: typeof import('ant-design-vue/es')['CheckboxGroup']
    AConfigProvider: typeof import('ant-design-vue/es')['ConfigProvider']
    ADatePicker: typeof import('ant-design-vue/es')['DatePicker']
    ADivider: typeof import('ant-design-vue/es')['Divider']
    ADropdown: typeof import('ant-design-vue/es')['Dropdown']
    AEmpty: typeof import('ant-design-vue/es')['Empty']
    AFloatButton: typeof import('ant-design-vue/es')['FloatButton']
    AForm: typeof import('ant-design-vue/es')['Form']
    AFormItem: typeof import('ant-design-vue/es')['FormItem']
    AImage: typeof import('ant-design-vue/es')['Image']
    AInput: typeof import('ant-design-vue/es')['Input']
    AInputSearch: typeof import('ant-design-vue/es')['InputSearch']
    AList: typeof import('ant-design-vue/es')['List']
    AListItem: typeof import('ant-design-vue/es')['ListItem']
    AModal: typeof import('ant-design-vue/es')['Modal']
    APagination: typeof import('ant-design-vue/es')['Pagination']
    APopconfirm: typeof import('ant-design-vue/es')['Popconfirm']
    AppBottomBar: typeof import('./../components/AppBottomBar.vue')['default']
    AppLeftBar: typeof import('./../components/AppLeftBar.vue')['default']
    AppTopBar: typeof import('./../components/AppTopBar.vue')['default']
    ARadioButton: typeof import('ant-design-vue/es')['RadioButton']
    ARadioGroup: typeof import('ant-design-vue/es')['RadioGroup']
    ARangePicker: typeof import('ant-design-vue/es')['RangePicker']
    ASegmented: typeof import('ant-design-vue/es')['Segmented']
    ASelect: typeof import('ant-design-vue/es')['Select']
    ASelectOption: typeof import('ant-design-vue/es')['SelectOption']
    ASpin: typeof import('ant-design-vue/es')['Spin']
    ASwitch: typeof import('ant-design-vue/es')['Switch']
    ATable: typeof import('ant-design-vue/es')['Table']
    ATableColumn: typeof import('ant-design-vue/es')['TableColumn']
    ATag: typeof import('ant-design-vue/es')['Tag']
    ATextarea: typeof import('ant-design-vue/es')['Textarea']
    ATooltip: typeof import('ant-design-vue/es')['Tooltip']
    BilladmCategoryTagSetting: typeof import('./../components/settings_view/BilladmCategoryTagSetting.vue')['default']
    BilladmChart: typeof import('./../components/da_view/BilladmChart.vue')['default']
    BilladmChartLines: typeof import('./../components/da_view/BilladmChartLines.vue')['default']
    BilladmChartList: typeof import('./../components/da_view/BilladmChartList.vue')['default']
    BilladmChartView: typeof import('./../components/da_view/BilladmChartView.vue')['default']
    BilladmFileSelect: typeof import('./../components/BilladmFileSelect.vue')['default']
    BilladmPageHeader: typeof import('./../components/common/BilladmPageHeader.vue')['default']
    BilladmPageLayout: typeof import('./../components/common/BilladmPageLayout.vue')['default']
    BilladmStatisticsFooter: typeof import('./../components/common/BilladmStatisticsFooter.vue')['default']
    BilladmTemplateSetting: typeof import('./../components/settings_view/BilladmTemplateSetting.vue')['default']
    BilladmTimeRangePicker: typeof import('./../components/common/BilladmTimeRangePicker.vue')['default']
    CategoryColumn: typeof import('./../components/settings_view/CategoryColumn.vue')['default']
    DataAnalysisView: typeof import('./../components/da_view/DataAnalysisView.vue')['default']
    KeyEventAddModal: typeof import('./../components/key_event_view/KeyEventAddModal.vue')['default']
    KeyEventDetail: typeof import('./../components/key_event_view/KeyEventDetail.vue')['default']
    KeyEventImageGallery: typeof import('./../components/key_event_view/KeyEventImageGallery.vue')['default']
    KeyEventLinkedTr: typeof import('./../components/key_event_view/KeyEventLinkedTr.vue')['default']
    KeyEventList: typeof import('./../components/key_event_view/KeyEventList.vue')['default']
    KeyEventView: typeof import('./../components/key_event_view/KeyEventView.vue')['default']
    Layout: typeof import('./../components/Layout.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SettingsView: typeof import('./../components/settings_view/SettingsView.vue')['default']
    TagColumn: typeof import('./../components/settings_view/TagColumn.vue')['default']
    TransactionRecordFilter: typeof import('./../components/common/TransactionRecordFilter.vue')['default']
    TransactionRecordTable: typeof import('./../components/tr_view/TransactionRecordTable.vue')['default']
    TransactionRecordView: typeof import('./../components/tr_view/TransactionRecordView.vue')['default']
    TrSortModal: typeof import('./../components/tr_view/TrSortModal.vue')['default']
    WorkspaceSetting: typeof import('./../components/settings_view/WorkspaceSetting.vue')['default']
  }
}
